(define (read-words src)
  (let ((port (open-input-file src)) (res '()) (temp '()))
    (define (loop)
      (let ((char (read-char port)))
        (if (eof-object? char)
            (begin (close-input-port port) res)
            (if (char-whitespace? char)
                (begin (set! res (cons (list->string temp) res))
                       (set! temp '())
                       (loop))
                (begin (set! temp (cons char temp)) (loop))))))
  (loop)))
